/* DATA MGMT OF LOCAL ELECTIONS */

** defines directory **
cd "$maindir/data/admin/raw"
clear


**# ** unzip admin raw data **
local myfilelist : dir . files"*.zip"
foreach file of local myfilelist {
	unzipfile "`file'", replace
}


**# ** import in Stata and retrieve mayor info **
forvalues x=1990/2019 {
	local myfilelist : dir . files"*`x'*.csv"
	foreach file of local myfilelist {
		import delimited "`file'", delimiter(";") varnames(1) asdouble encoding(ISO-8859-1) stringcols(_all) clear 
		rename descrizione_regione regione
		rename descrizione_provincia provincia
		rename descrizione_comune comune
		rename popolazione_censita pop2
// 		gen mayor = 1 if descrizione_carica=="Sindaco"
// 		keep if mayor == 1 
// 		drop mayor
		gen nome_cognome=strtrim(cognome+" "+nome)
		gen anno=`x'
		drop data_ballottaggio sigla_provincia consiglieri_spettanti assessori_assegnati sigla_titolo_accademico cognome nome partito_lista_coalizione data_cessazione maggioritario_proporzionale descrizione_tempo_gestione data_nomina
		save mayors_`x'.dta, replace
	}
}


**# ** append data and save it **
use mayors_1990.dta, clear
forvalues x=1991/2019 {
	local myfilelist : dir . files"mayors_`x'*.dta"
	foreach file of local myfilelist {
		append using `file'
	}
}


**# ** data mgmt **

* format strings *
ds, has(type string) 
local strvars "`r(varlist)'"
format `strvars' %15s

* sort *
sort comune anno
order comune anno

* drop regioni *
ta regione
drop if substr(regione,1,8) == "TRENTINO" // recover somewhere else
drop if substr(regione,1,6) == "FRIULI" // recover somewhere else
drop if regione == "VALLE D'AOSTA" // recover somewhere else
drop if regione == "SICILIA" // recover somewhere else
drop if regione == "SARDEGNA" // recover somewhere else
// drop regione
drop codice_regione

* drop provincia *
// drop provincia
drop codice_provincia

* date mgmt *
split data_elezione, p("/")
rename data_elezione1 day
replace day = subinstr(day,"0","",.) if substr(day,1,1) == "0"
rename data_elezione2 month
replace month = subinstr(month,"0","",.) if substr(month,1,1) == "0"
rename data_elezione3 year
foreach var of varlist day month year {
	destring `var', replace
}
gen ele_date=mdy(month,day,year)
format ele_date %td
drop day month year data_elezione

* keep mayors elected post 1991 *
// keep if year(ele_date) >= 1991 

* destring population *
destring pop2, replace
rename pop2 pop

* gen education *
ta titolo_di_studio
gen educ = 0 if inlist(titolo_di_studio, "NESSUN TITOLO DI STUDIO POSSEDUTO", "LICENZA ELEMENTARE") 
replace educ = 1 if inlist(titolo_di_studio, "LICENZA MEDIA INFERIORE","TITOLI O DIPLOMI PROFESSIONALI POST LIC.ELEMENTARE","LICENZA DI SCUOLA MEDIA INF. O TITOLI EQUIPOLLENTI")
replace educ = 2 if inlist(titolo_di_studio, "LICENZA MEDIA SUPERIORE","TITOLI O DIPLOMI PROFESSIONALI POST MEDIA INFER.","LICENZA DI SCUOLA MEDIA SUP. O TITOLI EQUIPOLLENTI")
replace educ = 3 if inlist(titolo_di_studio, "TITOLI O DIPLOMI PROFESSIONALI POST MEDIA SUPER.","LAUREA  BREVE","LAUREA")
replace educ = 4 if inlist(titolo_di_studio, "ALTRI TITOLI  POST-LAUREA","SPECIALIZZAZIONE POST LAUREA / DOTTORATO DI RICERCA")

* in city born mayor *
replace sede_nascita = strtrim(substr(sede_nascita,1,length(sede_nascita)-4))
gen may_born_city = 1 if comune == sede_nascita
recode may_born_city .=0

* female dum *
gen female = 1 if sesso == "M"
recode female .=0

* gen codcom *
drop codice_comune
cap drop codcom
gen codcom = istat_codice_comune
replace codcom = substr(codcom,2,length(codcom)) if substr(codcom,1,1) == "0"
destring codcom, replace

* generate variable for previous role in public admin *
sort nome_cognome data_nascita sesso anno
bys nome_cognome data_nascita sesso (anno): gen asd=_n==1
replace asd = anno if asd == 1
recode asd 0=.
bys nome_cognome data_nascita sesso (anno): carryforward asd, replace
rename asd year_first_experience

* keep only mayors and compute experience in office *
keep if descrizione_carica == "Sindaco"
gen exp_in_office = 1 if year_first_experience != anno
replace exp_in_office = . if year_first_experience == year(ele_date)
recode exp_in_office .=0
drop descrizione_carica livello_carica

* drop duplicates *
duplicates drop codcom anno, force

* mgmt id vars *
foreach x of varlist comune regione provincia {
	rename `x' `x'_mayors
}

* age *
gen year_born = substr(data_nascita,length(data_nascita)-3,4)
destring year_born, replace
gen age = anno-year_born
gen age2 = age^2

* job *
replace professione=upper(professione)
gen job_type=.
foreach job in 	"DIRETTORI GENERALI E CATEGORIE SIMILARI DELLA PUBBLICA AMMINISTRAZIONE" ///
				"DIRETTORI E CATEGORIE SIMILARI DELLE AZIENDE  AGRICOLE,FORESTALI E ZOOTECNICHE" ///
				"DIRETTORI E CATEGORIE SIMILARI DELLE INDUSTRIE, DEI TRASPORTI, DEL CREDITO E DEI SERVIZI" ///
				"DIRETTORI E CATEGORIE SIMILARI DEL COMMERCIO" ///
				"MAGISTRATI E GIURISTI" ///
				"DIRETTORI E CATEGORIE SIMILARI DEI PUBBLICI ESERCIZI" ///
				"PRESIDI, CAPI DI ISTITUTI DI ISTRUZIONE E DIRETTORI DIDATTICI" ///
				"DIRIGENTI DI AMMINISTRAZIONI, ORGANI ED ENTI PUBBLICI" ///
				"IMPRENDITORI TITOLARI E AMMIN. DELEGATI DI IMPRESE INDUSTRIALI, DEI TRASPORTI, DEL CREDITO DEI SERVIZI" ///
				"IMPRENDITORI, AMMINISTRATORI, DIRETTORI, GESTORI E RESPONSABILI DI AZIENDE PRIVATE" ///
				"IMPRENDITORI TITOLARI E AMMIN. DELEGATI DI IMPRESE COMMERCIALI" "IMPRENDITORI, GESTORI E RESPONSABILI DI PICCOLE IMPRESE" ///
				{
replace job_type=1 if professione=="`job'"
}
foreach job in 	"INGEGNERI EDILI" ///
				"INGEGNERI, ARCHITETTI E ALTRI SPECIALISTI E TECNICI IN MATERIA DI SCIENZE INGEGNERISTICHE, SICUREZZA E TUTELA DEL TERRITORIO, DEGLI EDIFICI E DELL'AMBIENTE, QUALITA' INDUSTRIALE" ///
				"INGEGNERI (MECCANICI, METALLURGICO-MINERARI, ELETTROTECNICI, ELETTRONICI E IN TELECOMUNICAZIONI, CHIMICI, CIVILI, ECC.)" ///
				"ARCHITETTI" "ALTRI INGEGNERI" "ARCHITETTI, URBANISTI E SPECIALISTI DEL RECUPERO E DELLA CONSERVAZIONE DEL TERRITORIO" ///
				"PROFESSORI UNIVERSITARI E ASSIMILATI" "PROFESSORI DI SCUOLA SECONDARIA SUPERIORE E ASSIMILATI" ///
				"PROFESSORI DI SCUOLA SECONDARIA SUPERIORE E INFERIORE" "MEDICI CHIRURGHI GENERICI" "MEDICI CHIRURGHI SPECIALISTI" ///
				"FISICI, ASTRONOMI E GEOLOGI" "DOCENTI UNIVERSITARI (ORDINARI E ASSOCIATI)" "SPECIALISTI IN SCIENZE GIURIDICHE" "SCRITTORI, GIORNALISTI E PUBBLICISTI" ///
				"SPECIALISTI DELLA FORMAZIONE E DELLA RICERCA E ADDETTI A SERVIZI SCOLASTICI" ///
				"SPECIALISTI E TECNICI NELLE SCIENZE MATEMATICHE, FISICHE E NATURALI" ///
				"SPECIALISTI IN SCIENZE E ATTIVITࡇESTIONALI, COMMERCIALI E BANCARIE (ORGANIZZAZIONE E CONTROLLO DEL LAVORO NELLE PUBBLICHE AMMINISTRAZIONI E NELLE IMPRESE PRIVATE, CONTABILITࡅ FINANZA, RAPPORTI CON IL MERCATO, PUBBLICHE RELAZIONI, ECC.)" ///
				"SPECIALISTI E TECNICI NELLE SCIENZE DELLA VITA" ///
				"SPECIALISTI E TECNICI NELLE SCIENZE DELLA SALUTE E ADDETTI A SERVIZI SANITARI" ///
				"SPECIALISTI E TECNICI IN SCIENZE E ATTIVITA' GESTIONALI, COMMERCIALI E BANCARIE" ///
				"BIOLOGI, BOTANICI E ZOOLOGI" "BIOLOGI, ZOOLOGI E NATURALISTI" "COMMERCIALISTI E ASSIMILATI" "CHIMICI" ///
				"PROFESSORI DI ACCADEMIE, CONSERVATORI E ALTRE ISTITUZIONI SCOLASTICHE ASSIMILATE" "PSICOLOGI E PSICOTERAPEUTI" ///
				"MATEMATICI, STATISTICI, ATTUARI, ECONOMISTI E SOCIOLOGI" "MEDICI GENERICI" "PARAMEDICI (INFERMIERI, OPTOMETRISTI, ODONTOTECNICI, CHINESITERAPISTI, FISIOTERAPISTI, RIABILITATORI, LEVATRICI E OSTETRICHE DIPLOMATE, DIETISTI, IGIENISTI, PODOLOGI, ASSISTENTI MEDICI, ECC.)" ///
				{
replace job_type=2 if professione=="`job'"
}
foreach job in 	"ANALISTI E PROGRAMMATORI DI CALCOLATORI ELETTRONICI E DI MACCHINE CONTABILI" ///
				"AGRONOMI, PERITI AGRARI, FORESTALI, ZOOTECNICI, E ASSIMILATI" "ASSISTENTI, TECNICI SANITARI E ASSIMILATI" ///
				"AVVOCATI E PROCURATORI LEGALI" "PROFESSORI DI SCUOLA MEDIA E ASSIMILATI" "DENTISTI" "DISEGNATORI TECNICI E CARTOGRAFI" ///
				"FARMACISTI" "GEOMETRI E PERITI EDILI" "INFERMIERI E ASSIMILATI" "INSEGNANTI DI SCUOLA ELEMENTARE E ASSIMILATI" ///
				"INSEGNANTI NON ALTROVE CLASSIFICATI" "LAVORATORI AGRICOLI SPECIALIZZATI" ///
				"PROCURATORI LEGALI E AVVOCATI ED ESPERTI LEGALI IN IMPRESE O ENTI PUBBLICI" "VETERINARI" ///
				"PERITI INDUSTRIALI, PERITI CHIMICI, PERITI D'ARTE E ASSIMILATI" "OPERATORI RADIOGRAFICI, OTTICI, ODONTOTECNICI E ASSIMILATI" /// 
				"TECNICI CON MANSIONI DIRETTIVE E DI CONCETTO ESCLUSE LE PROFESIONI AGRICOLE" ///
				"TECNICI DELLA RADIO, DELLA TELEVISIONE, DEL CINEMA E OPERATORI DI PROIEZIONE" ///
				"TECNICI E OPERATORI DI APPARECCHI MEDICALI, OTTICI E PER LA DIAGNOSTICA MEDICA" ///
				"SPECIALISTI IN DIAGNOSTICA PER IMMAGINI E RADIOTERAPIA" ///
				"SPECIALISTI IN DISCIPLINE ARTISTICO-ESPRESSIVE (PITTORI, SCULTORI, RESTAURATORI D'ARTE, REGISTI, DIRETTORI ARTISTICI, ATTORI, SCENEGGIATORI, SCENOGRAFI, COREOGRAFI, BALLERINI, COMPOSITORI, MUSICISTI, CANTANTI, ECC.)" ///
				"SPECIALISTI IN DISCIPLINE LINGUISTICHE, LETTERARIE E DOCUMENTALI" ///
				"SPECIALISTI IN DISCIPLINE RELIGIOSE E TEOLOGICHE, MINISTRI DI CULTO E TECNICI O ADDETTI A SERVIZI RELIGIOSI E DI CULTO" ///
				"SPECIALISTI IN IGIENE, EPIDEMIOLOGIA E SANITà PUBBLICA" ///
				"SPECIALISTI IN SCIENZE E ATTIVITà GESTIONALI, COMMERCIALI E BANCARIE (ORGANIZZAZIONE E CONTROLLO DEL LAVORO NELLE PUBBLICHE AMMINISTRAZIONI E NELLE IMPRESE PRIVATE, CONTABILITà E FINANZA, RAPPORTI CON IL MERCATO, PUBBLICHE RELAZIONI, ECC.)" ///
				"SPECIALISTI IN SCIENZE SOCIALI (SCIENZE ECONOMICHE, SOCIOLOGICHE, ANTROPOLOGICHE, PSICOLOGICHE, STORICHE, ARTISTICHE, POLITICHE, FILOSOFICHE)" ///
				"SPECIALISTI IN SCIENZE SOCIALI E TECNICI DEI SERVIZI SOCIO-ASSISTENZIALI" ///
				"SPECIALISTI, ISTRUTTORI E TECNICI IN DISCIPLINE ARTISTICO-ESPRESSIVE, ATTIVITA' SPORTIVE E SERVIZI RICREATIVI E CULTURALI" ///
				"OSTETRICHE" ///
				"TECNICI DEI RAPPORTI CON I MERCATI E DELLA DISTRIBUZIONE COMMERCIALE (APPROVVIGIONATORI E RESPONSABILI ACQUISTI, RESPONSABILI DI MAGAZZINO E DELLA DISTRIBUZIONE INTERNA, STIMATORI E AGGIUDICATORI D'ASTA COMMERCIALI, TECNICI DELLA VENDITA E DELLA DISTRIBUZ" ///
				"TECNICI DEI SERVIZI PUBBLICI DI SICUREZZA E VIGILANZA (TECNICI DEI SERVIZI GIUDIZIARI, CONTROLLORI FISCALI, TECNICI DEI SERVIZI PUBBLICI DI CONCESSIONI E LICENZE, ECC.)" ///
				"TECNICI DEI SERVIZI RICREATIVI E CULTURALI (ANNUNCIATORI E PRESENTATORI DELLA RADIO, DELLA TELEVISIONE E DI ALTRI SPETTACOLI, DISEGNATORI ARTISTICI, TECNICI DEI MUSEI E DELLE BIBLIOTECHE, PERITI E STIMATORI D'ARTE, TECNICI DELL'ORGANIZZAZIONE DELLA PRODUZ" ///
				"TECNICI DEI SERVIZI SOCIALI E ASSISTENZIALI (ASSISTENTI SOCIALI, TECNICI DELLA ASSISTENZA E DELLA PREVIDENZA SOCIALE, TECNICI DEI SERVIZI DI INFORMAZIONE ED ORIENTAMENTO SCOLASTICO E PROFESSIONALE E DI COLLOCAMENTO, ECC.)" ///
				"TECNICI DELLA SICUREZZA, DELLA PROTEZIONE AMBIENTALE E DELLA QUALITà INDUSTRIALE (SICUREZZA DEGLI EDIFICI E SICUREZZA SUL LAVORO, CONTROLLO DELLA QUALITà INDUSTRIALE E AMBIENTALE, SMALTIMENTO DEI RIFIUTI, ECC.)" ///
				"TECNICI DELLE ATTIVITà TURISTICHE E RICETTIVE (AGENTI DI VIAGGIO, GUIDE ED ACCOMPAGNATORI SPECIALIZZATI, ANIMATORI TURISTICI, TECNICI DELL'ORGANIZZAZIONE DI FIERE E CONVEGNI, ECC.)" ///
				"TECNICI DELLE SCIENZE INGEGNERISTICHE (TECNICI MECCANICI, METALLURGICO-MINERARI, ELETTROTECNICI, ELETTRONICI, DELLE COSTRUZIONI CIVILI, DISEGNATORI INDUSTRIALI, ECC.)" ///
				"TECNICI DELLE SCIENZE QUANTITATIVE, FISICHE E CHIMICHE (TECNICI FISICI, CHIMICI, INFORMATICI E STATISTICI)" ///
				"TECNICI DI IMPIANTI NUCLEARI" ///
				"TECNICI E ADDETTI AD ATTIVITà FINANZIARIE ED ASSICURATIVE (AGENTI ASSICURATIVI, PERITI, VALUTATORI DI RISCHIO, LIQUIDATORI, AGENTI DI BORSA E CAMBIO, TECNICI DELL'INTERMEDIAZIONE TITOLI, ADDETTI A SPORTELLI BANCARI E ASSICURATIVI, ADDETTI AD AGENZIE DI PE" ///
				"TECNICI E ADDETTI AL TRASPORTO AEREO E NAVALE (TECNICI E COMANDANTI NAVALI, PILOTI DI AEREO, TECNICI DELL'AVIAZIONE CIVILE, CONTROLLORI E TECNICI DEL TRAFFICO AEREO, HOSTESS E STEWARD, ECC.)" ///
				"TECNICI E OPERATORI DI APPARECCHIATURE ELETTRONICHE (FOTOGRAFI, OPERATORI DI APPARECCHI PER LA TRASMISSIONE RADIO-TELEVISIVA E PER LE TELECOMUNICAZIONI O PER LA RIPRESA E LA PRODUZIONE AUDIO-VIDEO, ECC.)" ///
				"TECNICI NELLE SCIENZE DELLA VITA (ZOOTECNICI, TECNICI BIOCHIMICI, TECNICI AGRONOMI E FORESTALI, ECC.)" ///
				{
replace job_type=3 if professione=="`job'"
}
foreach job in 	"IMPIEGATI  AMMINISTRATIVI CON MANSIONI DIRETTIVE E DI CONCETTO" ///
				"IMPIEGATI  AMMINISTRATIVI NON ALTROVE CLASSIFICATI" "IMPIEGATI DI AMMINISTRAZIONI, ORGANI ED ENTI PUBBLICI (NON RICOMPRESI IN ALTRE SPECIFICHE CLASSIFICAZIONI)" ///
				"IMPIEGATI DI AZIENDE, IMPRESE, ENTI ECONOMICI E SOGGETTI DI DIRITTO PRIVATO CON QUALIFICHE DIRETTIVE" ///
				"IMPIEGATI DI AMMINISTRAZIONI, ORGANI ED ENTI PUBBLICI CON QUALIFICHE DIRETTIVE" ///
				"IMPIEGATI DI AZIENDE, IMPRESE, ENTI ECONOMICI E SOGGETTI DI DIRITTO PRIVATO (NON RICOMPRESI IN ALTRE SPECIFICHE CLASSIFICAZIONI)" ///
				"OPERATORI DI CALCOLATORI ELETTRONICI, DI MACCHINE TRADIZIONALI E ASSIMILATI" ///
				"ADDETTI AD ATTIVITࡁUSILIARIE DI UFFICIO (USCIERI, COMMESSI, LETTORI DI CONTATORI, ECC.) O DI MAGAZZINO, SPOSTAMENTO MERCI E COMUNICAZIONI (FACCHINI, ADDETTI ALLO SPOSTAMENTO, IMBALLAGGIO E CONSEGNA MERCI E AL MAGAZZINO, PORTALETTERE E FATTORINI, CENTRAL" ///
				"IMPIEGATI DI AMMINISTRAZIONI, ORGANI ED ENTI PUBBLICI CON QUALIFICHE NON DIRETTIVE" ///
				"DATTILOGRAFI E STENOGRAFI" {
replace job_type=4 if professione=="`job'"
}
foreach job in 	"CONTABILI, ECONOMI, CASSIERI NON ALTROVE CLASSIFICATI" ///
				"RAPPRESENTANTI DI COMMERCIO, VIAGGIATORI, MEDIATORI E ASSIMILATI" ///
				"RAPPRESENTANTI E MEDIATORI DEL CREDITO E ASSICURAZIONI, DEI TRASPORTI E DEI SERVIZI" ///
				"COMMERCIANTI E ESERCENTI DI NEGOZIO" ///
				"ASSISTENTI DI VOLO E GUIDE TURISTICHE" "ASSISTENTI SOCIALI" "ATLETI, ALLENATORI E ASSIMILATI" ///
				"BARISTI E ASSIMILATI" "BIBLIOTECARI, IMPIEGATI DI ARCHIVIO E ASSIMILATI" "CAPITRENO E ASSIMILATI" ///
				"ELETTRICISTI" "ELETTROTECNICI" "ESERCENTI DI ALBERGHI, RISTORANTI E ASSIMILATI" ///
				"ESERCENTI DI BAR, CAFFE' E ASSIMILATI" "ESERCENTI E GESTORI DI CINEMA,TEATRI E SIMILI" ///
				"ESERCENTI O ADDETTI AD ATTIVITA' COMMERCIALI O A SERVIZI ALLE PERSONE" ///
				"ESERCENTI O ADDETTI AD ATTIVITA' AGRICOLE, FORESTALI, DI ALLEVAMENTO, CACCIA E PESCA" ///
				"ESERCENTI E GESTORI DI CINEMA,TEATRI E SIMILI" "GUARDIANI, CUSTODI DI AZIENDE, GUARDIE CAMPESTRI E  ASSIMILATI" ///
				"IDRAULICI, STAGNINI E TERMOIDRAULICI" "MECCANICI GENERICI E RIPARATORI MECCANICI" "MECCANICI E RIPARATORI DI PROTESI DENTALI E ORTOPEDICHE" ///
				"MURATORI" "PORTALETTERE E FATTORINI POSTALI" "ALTRI LAVORATORI DEL COMMERCIO NON ALTROVE CLASSIFICATI" ///
				"PARRUCCHIERI ED ESTETISTI E TECNICI DELLA CURA ESTETICA" "BARBIERI, PARRUCCHIERI, MANICURE E ASSIMILATI" ///
				{
replace job_type=5 if professione=="`job'"
}
foreach job in 	"ARTIGIANI E OPERAI SPECIALIZZATI" "SARTI E CONFEZIONATORI DI PELLICCE" "PITTORI, SCULTORI E ASSIMILATI" ///
				"BORSETTAI, VALIGIAI E ASSIMILATI" "CARTAI E CARTONAI" "CASSIERI DI NEGOZI" "COMMERCIANTI AMBULANTI" ///
				"FABBRIFERRAI E FUCINATORI" "FALEGNAMI E MOBILIERI IN LEGNO E FORMICA" "FORNACIAI DI LATERIZI" ///
				"LAVORATORI AGRICOLI GENERICI" "LAVORATORI FORESTALI E BOSCHIVI" "TECNICI CON MANSIONI ESECUTIVE ESCLUSE LE PROFESSIONI AGRICOLE" ///
				"TORNITORI,INTAGLIATORI,INCISORI,DEL LEGNO E ASSIMILATI" "VERNICIATORI E LUCIDATORI DEL LEGNO E PAGLIA" ///
				"VETRAI" "VINIFICATORI, BIRRAI, LAVORATORI DI ACQUE MINERALI, DI BEVANDE ALCOOLICHE E ANALCOOLICHE" "TESSITORI" ///
				"OPERAI ADDETTI ALLA ESTRAZIONE E ALLA PREPARAZIONEDEI MINERALI NON ALTROVE CLASSIFICATI" ///
				"PANETTIERI E PASTAI" {
replace job_type=6 if professione=="`job'"
}
foreach job in 	"CONDUTTORI DI AZIENDE AD ORDINAMENTO PRODUTTIVO MISTO E ASSIMILATI" ///
				"CONDUTTORI DI AZIENDE AD ORDINAMENTO PRODUTTIVO SPECIALIZZATO E ASSIMILATI" ///
				"CONDUTTORI ALLEVATORI E ASSIMILATI" "CONTONIERI STRADALI E FERROVIARI" "ADDETTI AI TRASPORTI TERRESTRI NON ALTROVE CLASSIFICATI" ///
				"CONDUTTORI DI IMPIANTI E DI VEICOLI, TECNICI, OPERAI SEMIQUALIFICATI E ALTRI ADDETTI A MACCHINARI FISSI E MOBILI E AD ATTIVITA' INDUSTRIALI" ///
				"DEVIATORI, MONOVRATORI, FRENATORI, FERROVIARI E TRAMVIARI" "MACCHINISTI FERROVIARI E ASSIMILATI" ///
				"ADDETTI ALLA CONDUZIONE DI IMBARCAZIONI A MOTORE, A REMI, A VELA" ///
				"ADDETTI AI TRASPORTI AEREI NON ALTROVE CLASSIFICATI" ///
				"AUTISTI" "PILOTI DI AEROMOBILI, MOTORISTI DI BORDO E ASSIMI LATI" ///
				"CONDUCENTI DI MACCHINE AGRICOLE" "CONDUCENTI DI TRAMVIE E SIMILI" ///
				"CONDUCENTI DI VEICOLI A TRAZIONE ANIMALE E ASSIMILATI" ///
				"CONDUTTORI DI ALTRI MACCHINARI MOBILI E DI SOLLEVAMENTO (MACCHINE DI SOLLEVAMENTO TERRA, ECC.)" ///
				"CONDUTTORI DI IMPIANTI TERMICI E ASSIMILATI" ///
				"CONDUTTORI DI MACCHINE EDILI E ASSIMILATI" ///
				"CONDUTTORI DI VEICOLI PER IL TRASPORTO DI TERRA (MANOVRATORI DI IMPIANTI DI FUNIVIA, MOTOVEICOLI, CONDUTTORI DI LOCOMOTIVE, AUTOBUS, CAMION, TAXI E ALTRI AUTOVEICOLI E DI VEICOLI A TRAZIONE ANIMALE, ECC.)" ///
				{ 
replace job_type=7 if professione=="`job'"
}
foreach job in 	"CONDIZIONI NON PROFESSIONALI" "PERSONE RITIRATE DAL LAVORO" "SCOLARI E STUDENTI" ///
				"PROFESSIONI NON ALTROVE CLASSIFICABILI" "PENSIONATI E PERSONE RITIRATE DAL LAVORO" "PERSONE IN CERCA DI PRIMA OCCUPAZIONE" ///
				"ADDETTI AI SERVIZI NON ALTROVE CLASSIFICATI" "CULTORI DI DISCIPLINE NON ALTROVE CLASSIFICATI" ///
				"DISOCCUPATI" "DISOCCUPATI E INOCCUPATI" "OPERAI METALLURGICI NON ALTROVE CLASSIFICATI" ///
				"ADDETTI AD ALTRE ATTIVITà COMMERCIALI NON QUALIFICATE (VENDITORI AMBULANTI, PERSONALE ADDETTO ALLA PULIZIA IN ESERCIZI ALBERGHIERI ED EXTRALBERGHIERI, ECC.)" ///
				"ADDETTI AD ALTRE ATTIVITà NON QUALIFICATE DELLE MINIERE, DELLE COSTRUZIONI E DELL'INDUSTRIA (MANOVALI, ECC.)" ///
				"ADDETTI AD ALTRI SERVIZI ALLE PERSONE NON QUALIFICATI (ADDETTI A SERVIZI RICREATIVI E CULTURALI, COLLABORATORI DOMESTICI, ADDETTI ALLA SORVEGLIANZA DI BAMBINI, SPAZZINI, ADDETTI A SERVIZI DI PULIZIA IN IMPRESE ED ENTI PUBBLICI, ADDETTI A SERVIZI DI LAVAND" ///
				"ADDETTI AD ATTIVITà AUSILIARIE DI UFFICIO (USCIERI, COMMESSI, LETTORI DI CONTATORI, ECC.) O DI MAGAZZINO, SPOSTAMENTO MERCI E COMUNICAZIONI (FACCHINI, ADDETTI ALLO SPOSTAMENTO, IMBALLAGGIO E CONSEGNA MERCI E AL MAGAZZINO, PORTALETTERE E FATTORINI, CENTRAL" ///
				"ADDETTI AD ATTIVITà NON QUALIFICATE DELL'AGRICOLTURA, DELL'ALLEVAMENTO, DELLA PESCA E DELLA FORESTAZIONE (BRACCIANTI AGRICOLI, ADDETTI ALLE CURE DEGLI ANIMALI, ECC.)" ///
				"CASALINGHE" "MANOVALI EDILI,STERRATORI E ASSIMILATI" ///
				"ADDETTI ALL'ASSISTENZA ALLE PERSONE E ALLE FAMIGLIE" "STUDENTI" "COMMESSI, USCIERI, BIDELLI, INSERVIENTI DI UFFICI PUBBLICI E PRIVATI" ///
				{
replace job_type=8 if professione=="`job'"
}
foreach job in 	"UFFICIALI DELLE FORZE ARMATE" "UFFICIALI DEI CARABINIERI, DI POLIZIA, DELLA GUARDIADI FINANZA, DEI VIGILI DEL FUOCO E ASSIMILATI" ///
				"CARABINIERI, AGENTI DI POLIZIA, GUARDIE DI FINANZA, VIGILI DEL FUOCO E ASSIMILATI"  ///
				"APPARTENENTI A FORZE ARMATE E A FORZE DI POLIZIA, TECNICI E ADDETTI A SERVIZI DI SICUREZZA PUBBLICA E VIGILANZA PUBBLICA E PRIVATA" ///
				"SOTTUFFICIALI" "SOTTUFFICIALI DEI CARABINIERI, DI POLIZIA, DELLA GUARDIA DI FINANZA, DEI VIGILI DEL FUOCO E ASSIMILATI" ///
				"SOTTUFFICIALI E MILITARI DELLE FORZE ARMATE" "UFFICIALI" {
replace job_type=9 if professione=="`job'"
}
ta professione if job_type==.
recode job_type .=99 if professione!=""
forvalues x=1/9 {
	gen job_cpi_`x'=1 if job_type==`x'
	recode job_cpi_`x' .=0
}

* keep relevant vars *
keep comune_mayors ele_date anno regione_mayors provincia_mayors istat_codice_comune pop educ may_born_city female codcom year_born age age2 nome_cognome job_type job_cpi* exp_in_office

* last mgmt *
rename nome_cognome name_winner
keep if anno == year(ele_date)
drop if anno == 1990


** save dataset **
save "$maindir/data/admin/mayors_chars_0525.dta", replace



